theme: jekyll-theme-cayman
# theme: minima
title: Hansen He Lab
author: Hansen He Lab
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An Epigenetics Lab Based in Toronto, Canada
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  HansenHeLab # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
