# Site settings
# theme: jekyll-theme-cayman
theme: minima
title: Hansen He Lab
# author: Hansen He Lab
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An Epigenetics Lab based in Toronto, Canada
baseurl: ''
# url: 'http://localhost:4000'
url: 'http://hansenhelab.github.io'
# social links
twitter_username: hansenhe7 # DO NOT include the @ character, or else the build will fail!
github_username:  HansenHeLab # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

# Build Settings
include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
