# Site settings
# theme: jekyll-theme-cayman
theme: minima
title: Hansen He Lab
# author: Hansen He Lab
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An Epigenetics Lab based in Toronto, Canada
baseurl: ''
url: 'http://localhost:4000'
# url: 'http://hansenhelab.github.io'
# social links
twitter_username: hansenhe7 # DO NOT include the @ character, or else the build will fail!
github_username:  HansenHeLab # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
